# resolver: lts-15.4
resolver: nightly-2020-06-25

compiler: ghc-8.10.1

packages:
- .

extra-deps:
- smtp-mail-0.3.0.0
- github: PLSysSec/frankie
  commit: b9ee2c0f7667025d0d0ac3a43ded43d1d1d63c28
- github: binah-framework/binah
  commit: d24fbaa0ceb4c11f48bb0d8e9b89ac72c57ee194


# LH stuff
- text-format-0.3.2
- Diff-0.3.4
- liquid-fixpoint-0.8.10.1
- liquidhaskell-0.8.10.1
- liquid-base-4.14.0.0
- liquid-ghc-prim-0.6.1
